# .github/workflows/jekyll-deploy.yml
name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main # Or whatever branch you use for your source code, e.g., 'master'
  pull_request:
    branches:
      - main # Or 'master'
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Fetch all history for jekyll-feed and jekyll-sitemap

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Important: Match your local Ruby version, or ensure it's compatible with Chirpy
          bundler-cache: true # Installs gems and caches them

      - name: Install dependencies (Chirpy specific)
        run: |
          # Install necessary packages for Chirpy's assets build
          sudo apt-get update
          sudo apt-get install -y imagemagick # Often needed for image processing

      - name: Build Jekyll site
        run: bundle exec jekyll build --verbose # --verbose can help debug if issues persist

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site # This is the directory Jekyll builds into

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
